[project]
name = "redstone-clarity-connector"
authors = []
description = ""
telemetry = false
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.redstone-receiver]
path = "contracts/redstone-receiver.clar"
depends_on = []
